import '../../data/models/tuition_class.dart';

class MockClassData {
  static List<TuitionClass> getMockClasses() {
    final DateTime now = DateTime.now();

    return [
      TuitionClass(
        id: '1',
        name: 'Grade 10 Mathematics',
        subject: 'Mathematics',
        description: 'Advanced mathematics for Grade 10 students',
        monthlyFee: 3500,
        teacherId: 'teacher1',
        startDate: now.subtract(const Duration(days: 30)),
        schedule: 'Monday, Wednesday - 4:00 PM',
        maxStudents: 30,
        currentStudents: 25,
        isActive: true,
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '2',
        name: 'Grade 11 Science',
        subject: 'Science',
        description: 'Science for Grade 11 O/L students',
        monthlyFee: 4000,
        teacherId: 'teacher2',
        startDate: now.subtract(const Duration(days: 60)),
        schedule: 'Tuesday, Thursday - 5:00 PM',
        maxStudents: 25,
        currentStudents: 25,
        isActive: true,
        createdAt: now.subtract(const Duration(days: 75)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '3',
        name: 'A/L Physics',
        subject: 'Physics',
        description: 'Physics for Advanced Level students',
        monthlyFee: 5000,
        teacherId: 'teacher3',
        startDate: now.subtract(const Duration(days: 45)),
        schedule: 'Saturday - 8:00 AM to 12:00 PM',
        maxStudents: 20,
        currentStudents: 18,
        isActive: true,
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '4',
        name: 'A/L Chemistry',
        subject: 'Chemistry',
        description: 'Chemistry for Advanced Level students',
        monthlyFee: 5000,
        teacherId: 'teacher1',
        startDate: now.subtract(const Duration(days: 45)),
        schedule: 'Sunday - 8:00 AM to 12:00 PM',
        maxStudents: 20,
        currentStudents: 15,
        isActive: true,
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '5',
        name: 'Grade 9 English',
        subject: 'English',
        description: 'English language class for Grade 9 students',
        monthlyFee: 3000,
        teacherId: 'teacher4',
        startDate: now.subtract(const Duration(days: 15)),
        schedule: 'Friday - 3:00 PM to 5:00 PM',
        maxStudents: 30,
        currentStudents: 12,
        isActive: true,
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '6',
        name: 'Grade 8 Mathematics',
        subject: 'Mathematics',
        description: 'Mathematics for Grade 8 students',
        monthlyFee: 3000,
        teacherId: 'teacher1',
        startDate: now.subtract(const Duration(days: 90)),
        endDate: now.subtract(const Duration(days: 10)),
        schedule: 'Monday, Wednesday - 2:00 PM',
        maxStudents: 25,
        currentStudents: 20,
        isActive: false,
        createdAt: now.subtract(const Duration(days: 100)),
        updatedAt: now.subtract(const Duration(days: 10)),
      ),
    ];
  }
}
