import '../../data/models/student.dart';

class MockStudentData {
  static List<Student> getMockStudents() {
    final DateTime now = DateTime.now();

    return [
      Student(
        id: '1',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phone: '0771234567',
        parentPhone: '0777654321',
        address: 'No. 123, Main Street, Colombo',
        school: 'Royal College',
        grade: 'Grade 10',
        teacherId: 'teacher1',
        classIds: ['1', '4'],
        isActive: true,
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now,
      ),
      Student(
        id: '2',
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        phone: '0772345678',
        parentPhone: '0778765432',
        address: 'No. 456, Park Avenue, Nugegoda',
        school: 'Visakha College',
        grade: 'Grade 11',
        teacherId: 'teacher2',
        classIds: ['2'],
        isActive: true,
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now,
      ),
      Student(
        id: '3',
        firstName: 'David',
        lastName: 'Fernando',
        email: 'david.f@example.com',
        phone: '0773456789',
        parentPhone: '0779876543',
        address: 'No. 789, Lake Road, Rajagiriya',
        school: 'Isipathana College',
        grade: 'A/L',
        teacherId: 'teacher3',
        classIds: ['3'],
        isActive: true,
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now,
      ),
      Student(
        id: '4',
        firstName: 'Sarah',
        lastName: 'Perera',
        email: 'sarah.p@example.com',
        phone: '0774567890',
        parentPhone: '0770987654',
        address: 'No. 101, Hill Street, Dehiwala',
        school: 'Musaeus College',
        grade: 'A/L',
        teacherId: 'teacher1',
        classIds: ['3', '4'],
        isActive: true,
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now,
      ),
      Student(
        id: '5',
        firstName: 'Amal',
        lastName: 'Silva',
        email: 'amal.silva@example.com',
        phone: '0775678901',
        parentPhone: '0771098765',
        address: 'No. 202, Beach Road, Mount Lavinia',
        school: 'D.S. Senanayake College',
        grade: 'Grade 9',
        teacherId: 'teacher4',
        classIds: ['5'],
        isActive: true,
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
      ),
      Student(
        id: '6',
        firstName: 'Kamala',
        lastName: 'Gunasekara',
        email: 'kamala.g@example.com',
        phone: '0776789012',
        parentPhone: '0772109876',
        address: 'No. 303, Temple Road, Maharagama',
        school: 'Ananda College',
        grade: 'Grade 10',
        teacherId: 'teacher1',
        classIds: ['1'],
        isActive: false,
        createdAt: now.subtract(const Duration(days: 90)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
    ];
  }
}
