import '../../data/models/tuition_class.dart';

class MockClassData {
  static List<TuitionClass> getMockClasses() {
    final DateTime now = DateTime.now();

    Map<String, dynamic> mockTeacher = {
      "id": "cd544db9-7060-4ba1-8f72-c1472bd9dd27",
      "email": "test@gmail.com",
      "name": "Mock Teacher",
      "status": true,
    };

    return [
      TuitionClass(
        id: '1',
        name: 'Grade 10 Mathematics',
        subject: 'Mathematics',
        description: 'Advanced mathematics for Grade 10 students',
        monthlyFee: 3500,
        paymentDueDay: 15,
        usualScheduledOn: 'Monday, Wednesday - 4:00 PM',
        status: true,
        teacher: mockTeacher,
        teacherId: 'teacher1',
        startDate: now.subtract(const Duration(days: 30)),
        maxStudents: 30,
        currentStudents: 25,
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '2',
        name: 'Grade 11 Science',
        subject: 'Science',
        description: 'Science for Grade 11 O/L students',
        monthlyFee: 4000,
        paymentDueDay: 15,
        usualScheduledOn: 'Tuesday, Thursday - 5:00 PM',
        status: true,
        teacher: mockTeacher,
        teacherId: 'teacher2',
        startDate: now.subtract(const Duration(days: 60)),
        maxStudents: 25,
        currentStudents: 25,
        createdAt: now.subtract(const Duration(days: 75)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '3',
        name: 'A/L Physics',
        subject: 'Physics',
        description: 'Physics for Advanced Level students',
        monthlyFee: 5000,
        paymentDueDay: 20,
        usualScheduledOn: 'Saturday - 8:00 AM to 12:00 PM',
        status: true,
        teacher: mockTeacher,
        teacherId: 'teacher3',
        startDate: now.subtract(const Duration(days: 45)),
        maxStudents: 20,
        currentStudents: 18,
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '4',
        name: 'A/L Chemistry',
        subject: 'Chemistry',
        description: 'Chemistry for Advanced Level students',
        monthlyFee: 5000,
        paymentDueDay: 15,
        usualScheduledOn: 'Sunday - 8:00 AM to 12:00 PM',
        status: true,
        teacher: mockTeacher,
        teacherId: 'teacher1',
        startDate: now.subtract(const Duration(days: 45)),
        maxStudents: 20,
        currentStudents: 15,
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '5',
        name: 'Grade 9 English',
        subject: 'English',
        description: 'English language class for Grade 9 students',
        monthlyFee: 3000,
        paymentDueDay: 10,
        usualScheduledOn: 'Friday - 3:00 PM to 5:00 PM',
        status: true,
        teacher: mockTeacher,
        teacherId: 'teacher4',
        startDate: now.subtract(const Duration(days: 15)),
        maxStudents: 30,
        currentStudents: 12,
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now,
      ),
      TuitionClass(
        id: '6',
        name: 'Grade 8 Mathematics',
        subject: 'Mathematics',
        description: 'Mathematics for Grade 8 students',
        monthlyFee: 3000,
        paymentDueDay: 5,
        usualScheduledOn: 'Monday, Wednesday - 2:00 PM',
        status: false,
        teacher: mockTeacher,
        teacherId: 'teacher1',
        startDate: now.subtract(const Duration(days: 90)),
        endDate: now.subtract(const Duration(days: 10)),
        maxStudents: 25,
        currentStudents: 20,
        createdAt: now.subtract(const Duration(days: 100)),
        updatedAt: now.subtract(const Duration(days: 10)),
      ),
    ];
  }
}
